// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace LWMDev_UI_Tests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SearchPageFeature : object, Xunit.IClassFixture<SearchPageFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "SearchPage", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "SearchPage.feature"
#line hidden
        
        public SearchPageFeature(SearchPageFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Click search on the navigation bar")]
        [Xunit.TraitAttribute("FeatureTitle", "SearchPage")]
        [Xunit.TraitAttribute("Description", "Click search on the navigation bar")]
        [Xunit.InlineDataAttribute("chrome", new string[0])]
        [Xunit.InlineDataAttribute("firefox", new string[0])]
        [Xunit.InlineDataAttribute("edge", new string[0])]
        [Xunit.InlineDataAttribute("safari", new string[0])]
        public async System.Threading.Tasks.Task ClickSearchOnTheNavigationBar(string browser, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("browser", browser);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Click search on the navigation bar", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 3
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
 await testRunner.GivenAsync(string.Format("SearchPage: I use Browser \"{0}\"", browser), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 5
 await testRunner.WhenAsync("SearchPage: I go to \"https://localhost:44325/search\" and use the search button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 6
 await testRunner.ThenAsync("SearchPage: the page title is \"Search - Lewis Whittard Software Development\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Click home on the navigation bar")]
        [Xunit.TraitAttribute("FeatureTitle", "SearchPage")]
        [Xunit.TraitAttribute("Description", "Click home on the navigation bar")]
        [Xunit.InlineDataAttribute("chrome", new string[0])]
        [Xunit.InlineDataAttribute("firefox", new string[0])]
        [Xunit.InlineDataAttribute("edge", new string[0])]
        [Xunit.InlineDataAttribute("safari", new string[0])]
        public async System.Threading.Tasks.Task ClickHomeOnTheNavigationBar(string browser, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("browser", browser);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Click home on the navigation bar", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 15
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
 await testRunner.GivenAsync(string.Format("SearchPage: I use Browser \"{0}\"", browser), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 17
 await testRunner.WhenAsync("SearchPage: I go to \"https://localhost:44325/search\" and use the home button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 18
 await testRunner.ThenAsync("SearchPage: the page title is \"Home Page - Lewis Whittard Software Development\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Click Linkedin button")]
        [Xunit.TraitAttribute("FeatureTitle", "SearchPage")]
        [Xunit.TraitAttribute("Description", "Click Linkedin button")]
        [Xunit.InlineDataAttribute("chrome", new string[0])]
        [Xunit.InlineDataAttribute("firefox", new string[0])]
        [Xunit.InlineDataAttribute("edge", new string[0])]
        [Xunit.InlineDataAttribute("safari", new string[0])]
        public async System.Threading.Tasks.Task ClickLinkedinButton(string browser, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("browser", browser);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Click Linkedin button", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 27
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 28
 await testRunner.GivenAsync(string.Format("SearchPage: I use Browser \"{0}\"", browser), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 29
 await testRunner.WhenAsync("SearchPage: I go to \"https://localhost:44325/search\" and use the Linkedin button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 30
 await testRunner.ThenAsync("SearchPage: I have arrived at linkedin", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Click logo on the navigation bar")]
        [Xunit.TraitAttribute("FeatureTitle", "SearchPage")]
        [Xunit.TraitAttribute("Description", "Click logo on the navigation bar")]
        [Xunit.InlineDataAttribute("chrome", new string[0])]
        [Xunit.InlineDataAttribute("firefox", new string[0])]
        [Xunit.InlineDataAttribute("edge", new string[0])]
        [Xunit.InlineDataAttribute("safari", new string[0])]
        public async System.Threading.Tasks.Task ClickLogoOnTheNavigationBar(string browser, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("browser", browser);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Click logo on the navigation bar", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 39
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 40
 await testRunner.GivenAsync(string.Format("SearchPage: I use Browser \"{0}\"", browser), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 41
 await testRunner.WhenAsync("SearchPage: I go to \"https://localhost:44325/search\" and use the logo button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 42
 await testRunner.ThenAsync("SearchPage: the page title is \"Home Page - Lewis Whittard Software Development\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="I go to the search page")]
        [Xunit.TraitAttribute("FeatureTitle", "SearchPage")]
        [Xunit.TraitAttribute("Description", "I go to the search page")]
        [Xunit.InlineDataAttribute("chrome", new string[0])]
        [Xunit.InlineDataAttribute("firefox", new string[0])]
        [Xunit.InlineDataAttribute("edge", new string[0])]
        [Xunit.InlineDataAttribute("safari", new string[0])]
        public async System.Threading.Tasks.Task IGoToTheSearchPage(string browser, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("browser", browser);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("I go to the search page", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 51
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 52
 await testRunner.GivenAsync(string.Format("SearchPage: I use Browser \"{0}\"", browser), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 53
 await testRunner.WhenAsync("SearchPage: I go to \"https://localhost:44325/search\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 54
 await testRunner.ThenAsync("SearchPage: all search items should be visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Click Github button")]
        [Xunit.TraitAttribute("FeatureTitle", "SearchPage")]
        [Xunit.TraitAttribute("Description", "Click Github button")]
        [Xunit.InlineDataAttribute("chrome", new string[0])]
        [Xunit.InlineDataAttribute("firefox", new string[0])]
        [Xunit.InlineDataAttribute("edge", new string[0])]
        [Xunit.InlineDataAttribute("safari", new string[0])]
        public async System.Threading.Tasks.Task ClickGithubButton(string browser, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("browser", browser);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Click Github button", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 63
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 64
 await testRunner.GivenAsync(string.Format("SearchPage: I use Browser \"{0}\"", browser), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 65
 await testRunner.WhenAsync("SearchPage: I go to \"https://localhost:44325/search\" and use the Github button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 66
 await testRunner.ThenAsync("SearchPage: I have arrived at Github", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Click Software Development on the navigation bar")]
        [Xunit.TraitAttribute("FeatureTitle", "SearchPage")]
        [Xunit.TraitAttribute("Description", "Click Software Development on the navigation bar")]
        [Xunit.InlineDataAttribute("chrome", new string[0])]
        [Xunit.InlineDataAttribute("firefox", new string[0])]
        [Xunit.InlineDataAttribute("edge", new string[0])]
        [Xunit.InlineDataAttribute("safari", new string[0])]
        public async System.Threading.Tasks.Task ClickSoftwareDevelopmentOnTheNavigationBar(string browser, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("browser", browser);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Click Software Development on the navigation bar", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 75
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 76
 await testRunner.GivenAsync(string.Format("SearchPage: I use Browser \"{0}\"", browser), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 77
 await testRunner.WhenAsync("SearchPage: I go to \"https://localhost:44325/search\" and use the Software Develop" +
                        "ment button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 78
 await testRunner.ThenAsync("SearchPage: the page title is \"Software Development - Lewis Whittard Software Dev" +
                        "elopment\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Click Creative Works on the navigation bar")]
        [Xunit.TraitAttribute("FeatureTitle", "SearchPage")]
        [Xunit.TraitAttribute("Description", "Click Creative Works on the navigation bar")]
        [Xunit.InlineDataAttribute("chrome", new string[0])]
        [Xunit.InlineDataAttribute("firefox", new string[0])]
        [Xunit.InlineDataAttribute("edge", new string[0])]
        [Xunit.InlineDataAttribute("safari", new string[0])]
        public async System.Threading.Tasks.Task ClickCreativeWorksOnTheNavigationBar(string browser, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("browser", browser);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Click Creative Works on the navigation bar", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 87
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 88
 await testRunner.GivenAsync(string.Format("SearchPage: I use Browser \"{0}\"", browser), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 89
 await testRunner.WhenAsync("SearchPage: I go to \"https://localhost:44325/search\" and use the Creative Works b" +
                        "utton", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 90
 await testRunner.ThenAsync("SearchPage: the page title is \"Creative Works - Lewis Whittard Software Developme" +
                        "nt\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Search Category only All")]
        [Xunit.TraitAttribute("FeatureTitle", "SearchPage")]
        [Xunit.TraitAttribute("Description", "Search Category only All")]
        [Xunit.InlineDataAttribute("chrome", new string[0])]
        [Xunit.InlineDataAttribute("firefox", new string[0])]
        [Xunit.InlineDataAttribute("edge", new string[0])]
        [Xunit.InlineDataAttribute("safari", new string[0])]
        public async System.Threading.Tasks.Task SearchCategoryOnlyAll(string browser, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("browser", browser);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Search Category only All", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 99
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 100
 await testRunner.GivenAsync(string.Format("SearchPage: I use Browser \"{0}\"", browser), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 101
 await testRunner.WhenAsync("SearchPage: I go to \"https://localhost:44325/search\" select All and search", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 102
 await testRunner.ThenAsync("SearchPage: Then find the results based on the all category", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Search Category only Software Development")]
        [Xunit.TraitAttribute("FeatureTitle", "SearchPage")]
        [Xunit.TraitAttribute("Description", "Search Category only Software Development")]
        [Xunit.InlineDataAttribute("chrome", new string[0])]
        [Xunit.InlineDataAttribute("firefox", new string[0])]
        [Xunit.InlineDataAttribute("edge", new string[0])]
        [Xunit.InlineDataAttribute("safari", new string[0])]
        public async System.Threading.Tasks.Task SearchCategoryOnlySoftwareDevelopment(string browser, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("browser", browser);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Search Category only Software Development", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 111
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 112
 await testRunner.GivenAsync(string.Format("SearchPage: I use Browser \"{0}\"", browser), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 113
 await testRunner.WhenAsync("SearchPage: I go to \"https://localhost:44325/search\" select Software Development " +
                        "and search", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 114
 await testRunner.ThenAsync("SearchPage: Then find the results based on the Software Development category", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Search Category Creative Works - Mixed")]
        [Xunit.TraitAttribute("FeatureTitle", "SearchPage")]
        [Xunit.TraitAttribute("Description", "Search Category Creative Works - Mixed")]
        [Xunit.InlineDataAttribute("Chrome", "Cogetta", new string[0])]
        public async System.Threading.Tasks.Task SearchCategoryCreativeWorks_Mixed(string browser, string searchTerm, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("browser", browser);
            argumentsOfScenario.Add("searchTerm", searchTerm);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Search Category Creative Works - Mixed", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 123
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 124
    await testRunner.GivenAsync(string.Format("SearchPage: I use Browser \"{0}\"", browser), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 125
    await testRunner.WhenAsync(string.Format("SearchPage: I go to \"https://localhost:44325/search\" and select Creative Works an" +
                            "d search \"{0}\"", searchTerm), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 126
    await testRunner.ThenAsync("SearchPage: Then find the results based on the Creative Works category and Cogett" +
                        "a search", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Search Category Creative Works - Spesific")]
        [Xunit.TraitAttribute("FeatureTitle", "SearchPage")]
        [Xunit.TraitAttribute("Description", "Search Category Creative Works - Spesific")]
        [Xunit.InlineDataAttribute("Chrome", "Logo", new string[0])]
        public async System.Threading.Tasks.Task SearchCategoryCreativeWorks_Spesific(string browser, string searchTerm, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("browser", browser);
            argumentsOfScenario.Add("searchTerm", searchTerm);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Search Category Creative Works - Spesific", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 133
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 134
    await testRunner.GivenAsync(string.Format("SearchPage: I use Browser \"{0}\"", browser), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 135
    await testRunner.WhenAsync(string.Format("SearchPage: I go to \"https://localhost:44325/search\" and select Creative Works an" +
                            "d search \"{0}\"", searchTerm), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 136
    await testRunner.ThenAsync("SearchPage: Then find the results based on the Creative Works category and Logo s" +
                        "earch", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Search Category Creative Works - No Result")]
        [Xunit.TraitAttribute("FeatureTitle", "SearchPage")]
        [Xunit.TraitAttribute("Description", "Search Category Creative Works - No Result")]
        [Xunit.InlineDataAttribute("Chrome", "No Result", new string[0])]
        public async System.Threading.Tasks.Task SearchCategoryCreativeWorks_NoResult(string browser, string searchTerm, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("browser", browser);
            argumentsOfScenario.Add("searchTerm", searchTerm);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Search Category Creative Works - No Result", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 143
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 144
    await testRunner.GivenAsync(string.Format("SearchPage: I use Browser \"{0}\"", browser), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 145
    await testRunner.WhenAsync(string.Format("SearchPage: I go to \"https://localhost:44325/search\" and select Creative Works an" +
                            "d search \"{0}\"", searchTerm), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 146
    await testRunner.ThenAsync("SearchPage: Then find the results based on the Creative Works category and No Res" +
                        "ult", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Search Category All")]
        [Xunit.TraitAttribute("FeatureTitle", "SearchPage")]
        [Xunit.TraitAttribute("Description", "Search Category All")]
        [Xunit.InlineDataAttribute("chrome", new string[0])]
        [Xunit.InlineDataAttribute("firefox", new string[0])]
        [Xunit.InlineDataAttribute("edge", new string[0])]
        [Xunit.InlineDataAttribute("safari", new string[0])]
        public async System.Threading.Tasks.Task SearchCategoryAll(string browser, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("browser", browser);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Search Category All", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 152
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 153
 await testRunner.GivenAsync(string.Format("SearchPage: I use Browser \"{0}\"", browser), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 154
 await testRunner.WhenAsync("SearchPage: I go to \"https://localhost:44325/search\" select All and search", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 155
 await testRunner.ThenAsync("SearchPage: Then find the results based on the all category", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Search Category Software Development")]
        [Xunit.TraitAttribute("FeatureTitle", "SearchPage")]
        [Xunit.TraitAttribute("Description", "Search Category Software Development")]
        [Xunit.InlineDataAttribute("chrome", new string[0])]
        [Xunit.InlineDataAttribute("firefox", new string[0])]
        [Xunit.InlineDataAttribute("edge", new string[0])]
        [Xunit.InlineDataAttribute("safari", new string[0])]
        public async System.Threading.Tasks.Task SearchCategorySoftwareDevelopment(string browser, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("browser", browser);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Search Category Software Development", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 164
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 165
 await testRunner.GivenAsync(string.Format("SearchPage: I use Browser \"{0}\"", browser), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 166
 await testRunner.WhenAsync("SearchPage: I go to \"https://localhost:44325/search\" select Software Development " +
                        "and search", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 167
 await testRunner.ThenAsync("SearchPage: Then find the results based on the Software Development category", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Search Category Creative Works")]
        [Xunit.TraitAttribute("FeatureTitle", "SearchPage")]
        [Xunit.TraitAttribute("Description", "Search Category Creative Works")]
        [Xunit.InlineDataAttribute("chrome", new string[0])]
        [Xunit.InlineDataAttribute("firefox", new string[0])]
        [Xunit.InlineDataAttribute("edge", new string[0])]
        [Xunit.InlineDataAttribute("safari", new string[0])]
        public async System.Threading.Tasks.Task SearchCategoryCreativeWorks(string browser, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("browser", browser);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Search Category Creative Works", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 176
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 177
 await testRunner.GivenAsync(string.Format("SearchPage: I use Browser \"{0}\"", browser), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 178
 await testRunner.WhenAsync("SearchPage: I go to \"https://localhost:44325/search\" and select Creative Works an" +
                        "d search", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 179
 await testRunner.ThenAsync("SearchPage: Then find the results based on the Creative Works category", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Search Category Software development - Mixed")]
        [Xunit.TraitAttribute("FeatureTitle", "SearchPage")]
        [Xunit.TraitAttribute("Description", "Search Category Software development - Mixed")]
        [Xunit.InlineDataAttribute("Chrome", "Cogetta", new string[0])]
        public async System.Threading.Tasks.Task SearchCategorySoftwareDevelopment_Mixed(string browser, string searchTerm, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("browser", browser);
            argumentsOfScenario.Add("searchTerm", searchTerm);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Search Category Software development - Mixed", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 188
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 189
    await testRunner.GivenAsync(string.Format("SearchPage: I use Browser \"{0}\"", browser), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 190
    await testRunner.WhenAsync(string.Format("SearchPage: I go to \"https://localhost:44325/search\" and select Software Developm" +
                            "ent and search \"{0}\"", searchTerm), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 191
    await testRunner.ThenAsync("SearchPage: Then find the results based on the  Software Development category and" +
                        " Cogetta search", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Search Category Software development - Spesific")]
        [Xunit.TraitAttribute("FeatureTitle", "SearchPage")]
        [Xunit.TraitAttribute("Description", "Search Category Software development - Spesific")]
        [Xunit.InlineDataAttribute("Chrome", "Marginal gains", new string[0])]
        public async System.Threading.Tasks.Task SearchCategorySoftwareDevelopment_Spesific(string browser, string searchTerm, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("browser", browser);
            argumentsOfScenario.Add("searchTerm", searchTerm);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Search Category Software development - Spesific", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 198
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 199
    await testRunner.GivenAsync(string.Format("SearchPage: I use Browser \"{0}\"", browser), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 200
    await testRunner.WhenAsync(string.Format("SearchPage: I go to \"https://localhost:44325/search\" and select Software Developm" +
                            "ent and search \"{0}\"", searchTerm), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 201
    await testRunner.ThenAsync("SearchPage: Then find the results based on the Software Development category and " +
                        "Marginal gains", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Search Category Software development - No Result")]
        [Xunit.TraitAttribute("FeatureTitle", "SearchPage")]
        [Xunit.TraitAttribute("Description", "Search Category Software development - No Result")]
        [Xunit.InlineDataAttribute("Chrome", "No Result", new string[0])]
        public async System.Threading.Tasks.Task SearchCategorySoftwareDevelopment_NoResult(string browser, string searchTerm, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("browser", browser);
            argumentsOfScenario.Add("searchTerm", searchTerm);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Search Category Software development - No Result", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 208
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 209
    await testRunner.GivenAsync(string.Format("SearchPage: I use Browser \"{0}\"", browser), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 210
    await testRunner.WhenAsync(string.Format("SearchPage: I go to \"https://localhost:44325/search\" and select Software Developm" +
                            "ent and search \"{0}\"", searchTerm), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 211
    await testRunner.ThenAsync("SearchPage: Then find the results based on the Software Development category and " +
                        "No Result", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Search Category All - Mixed")]
        [Xunit.TraitAttribute("FeatureTitle", "SearchPage")]
        [Xunit.TraitAttribute("Description", "Search Category All - Mixed")]
        [Xunit.InlineDataAttribute("Chrome", "Cogetta", new string[0])]
        public async System.Threading.Tasks.Task SearchCategoryAll_Mixed(string browser, string searchTerm, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("browser", browser);
            argumentsOfScenario.Add("searchTerm", searchTerm);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Search Category All - Mixed", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 217
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 218
    await testRunner.GivenAsync(string.Format("SearchPage: I use Browser \"{0}\"", browser), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 219
    await testRunner.WhenAsync(string.Format("SearchPage: I go to \"https://localhost:44325/search\" and select all and search \"{" +
                            "0}\"", searchTerm), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 220
    await testRunner.ThenAsync("SearchPage: Then find the results based on the  all category and Cogetta search", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Search Category All - Software Development")]
        [Xunit.TraitAttribute("FeatureTitle", "SearchPage")]
        [Xunit.TraitAttribute("Description", "Search Category All - Software Development")]
        [Xunit.InlineDataAttribute("Chrome", "Marginal gains", new string[0])]
        [Xunit.InlineDataAttribute("Chrome", "", new string[0])]
        public async System.Threading.Tasks.Task SearchCategoryAll_SoftwareDevelopment(string browser, string searchTerm, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("browser", browser);
            argumentsOfScenario.Add("searchTerm", searchTerm);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Search Category All - Software Development", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 227
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 228
    await testRunner.GivenAsync(string.Format("SearchPage: I use Browser \"{0}\"", browser), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 229
    await testRunner.WhenAsync(string.Format("SearchPage: I go to \"https://localhost:44325/search\" and select all and search \"{" +
                            "0}\"", searchTerm), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 230
    await testRunner.ThenAsync("SearchPage: Then find the results based on the all category and Marginal gains", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Search Category All - No Result")]
        [Xunit.TraitAttribute("FeatureTitle", "SearchPage")]
        [Xunit.TraitAttribute("Description", "Search Category All - No Result")]
        [Xunit.InlineDataAttribute("Chrome", "No Result", new string[0])]
        public async System.Threading.Tasks.Task SearchCategoryAll_NoResult(string browser, string searchTerm, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("browser", browser);
            argumentsOfScenario.Add("searchTerm", searchTerm);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Search Category All - No Result", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 237
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 238
    await testRunner.GivenAsync(string.Format("SearchPage: I use Browser \"{0}\"", browser), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 239
    await testRunner.WhenAsync(string.Format("SearchPage: I go to \"https://localhost:44325/search\" and select all and search \"{" +
                            "0}\"", searchTerm), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 240
    await testRunner.ThenAsync("SearchPage: Then find the results based on the all category and No Result", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Search Category all - Creative Works")]
        [Xunit.TraitAttribute("FeatureTitle", "SearchPage")]
        [Xunit.TraitAttribute("Description", "Search Category all - Creative Works")]
        [Xunit.InlineDataAttribute("Chrome", "Logo", new string[0])]
        public async System.Threading.Tasks.Task SearchCategoryAll_CreativeWorks(string browser, string searchTerm, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("browser", browser);
            argumentsOfScenario.Add("searchTerm", searchTerm);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Search Category all - Creative Works", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 246
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 247
    await testRunner.GivenAsync(string.Format("SearchPage: I use Browser \"{0}\"", browser), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 248
    await testRunner.WhenAsync(string.Format("SearchPage: I go to \"https://localhost:44325/search\" and select all and search \"{" +
                            "0}\"", searchTerm), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 249
    await testRunner.ThenAsync("SearchPage: Then find the results based on the all category and Logo search", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await SearchPageFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await SearchPageFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
